# coding:[utf-8
color_dict = {
	0:  ['navy','white'],
	1:  ['blue','white'],
	2:  ['orange','black'],
	3:  ['red','black'],
	4:  ['green','black'],
	5:  ['purple','black'],
	6:  ['cyan','black'],
	7:  ['yellowgreen','black'],
	8:  ['yellow','black'],
	9:  ['black','white'],
	10: ['brown','black'],
	11: ['blanchedalmond','white'],
	12: ['blueviolet','black'],
	13: ['burlywood','black'],
	14: ['cadetblue','black'],
	15: ['aliceblue','black'],
	16: ['chocolate','black'],
	17: ['coral','black'],
	18: ['cornflowerblue','black'],
	19: ['cornsilk','black'],
	20: ['crimson','black'],
	21: ['gray','black'],
	22: ['darkorange','black'],
	23: ['whitesmoke','black'],
	24: ['darkgoldenrod','black'],
	25: ['white','black'],
	26: ['darkgreen','white'],
	27: ['wheat','black'],
	28: ['darkkhaki','black'],
	29: ['violet','black'],
	30: ['darkolivegreen','white'],
	31: ['aquamarine','black'],
	32: ['darkorchid','black'],
	33: ['turquoise','black'],
	34: ['darksalmon','black'],
	35: ['darkseagreen','black'],
	36: ['darkslateblue','black'],
	37: ['darkslategray','white'],
	38: ['darkslategrey','white'],
	39: ['darkturquoise','black'],
	40: ['darkviolet','black'],
	41: ['deeppink','black'],
	42: ['deepskyblue','black'],
	43: ['dimgray','white'],
	44: ['dimgrey','white'],
	45: ['dodgerblue','black'],
	46: ['firebrick','white'],
	47: ['floralwhite','black'],
	48: ['forestgreen','black'],
	49: ['tomato','black'],
	50: ['gainsboro','black'],
	51: ['ghostwhite','black'],
	52: ['gold','black'],
	53: ['goldenrod','black'],
	54: ['azure','white'],
	55: ['grey','white'],
	56: ['chartreuse','white'],
	57: ['greenyellow','black'],
	58: ['honeydew','black'],
	59: ['hotpink','black'],
	60: ['indianred','black'],
	61: ['indigo','white'],
	62: ['ivory','black'],
	63: ['khaki','black'],
	64: ['lavender','black'],
	65: ['lavenderblush','black'],
	66: ['lawngreen','black'],
	67: ['lemonchiffon','black'],
	68: ['lightblue','black'],
	69: ['lightcoral','black'],
	70: ['lightcyan','black'],
	71: ['lightgoldenrodyellow','black'],
	72: ['lightgray','black'],
	73: ['thistle','black'],
	74: ['lightgrey','black'],
	75: ['lightpink','black'],
	76: ['lightsalmon','black'],
	77: ['lightseagreen','black'],
	78: ['lightskyblue','black'],
	79: ['lightslategray','black'],
	80: ['lightslategrey','black'],
	81: ['lightsteelblue','black'],
	82: ['lightyellow','black'],
	83: ['tan','black'],
	84: ['limegreen','black'],
	85: ['linen','black'],
	86: ['magenta','black'],
	87: ['maroon','white'],
	88: ['mediumaquamarine','black'],
	89: ['mediumblue','white'],
	90: ['mediumorchid','black'],
	91: ['mediumpurple','black'],
	92: ['mediumseagreen','black'],
	93: ['mediumslateblue','black'],
	94: ['mediumspringgreen','black'],
	95: ['mediumturquoise','black'],
	96: ['mediumvioletred','black'],
	97: ['midnightblue','white'],
	98: ['mintcream','black'],
	99: ['mistyrose','black'],
	100:['moccasin','black'],
	101:['navajowhite','black'],
	102:['navy','white'],
	103:['oldlace','black'],
	104:['steelblue','black'],
	105:['olivedrab','black'],
	106:['beige','black'],
	107:['orangered','black'],
	108:['orchid','black'],
	109:['palegoldenrod','black'],
	110:['palegreen','black'],
	111:['paleturquoise','black'],
	112:['palevioletred','black'],
	113:['papayawhip','black'],
	114:['peachpuff','black'],
	115:['peru','black'],
	116:['pink','black'],
	117:['plum','black'],
	118:['powderblue','black'],
	119:['bisque','black'],
	120:['brown1','black'],
	121:['rosybrown','black'],
	122:['royalblue','black'],
	123:['saddlebrown','white'],
	124:['salmon','black'],
	125:['sandybrown','black'],
	126:['seagreen','black'],
	127:['seashell','black'],
	128:['sienna','black'],
	129:['springgreen','black'],
	130:['skyblue','black'],
	131:['slateblue','black'],
	132:['slategray','black'],
	133:['slategrey','black'],
	134:['snow','black'],
	135:['aquamarine','black']
}

color_dict_GRN = {
	1:  ['chartreuse','black'],
	2:  ['cyan','black'],
	3:  ['darkorange','black'],
	4:  ['brown1','black'],
	5:  ['purple','black'],
	6:  ['orange','black'],
	7:  ['yellowgreen','black'],
	8:  ['yellow','black'],
	9:  ['black','white'],
	10: ['brown','black'],
	11: ['blanchedalmond','black'],
	12: ['blueviolet','black'],
	13: ['burlywood','black'],
	14: ['cadetblue','black'],
	15: ['aliceblue','black'],
	16: ['chocolate','black'],
	17: ['coral','black'],
	18: ['cornflowerblue','black'],
	19: ['cornsilk','black'],
	20: ['crimson','black'],
	21: ['gray','black'],
	22: ['red','black'],
	23: ['whitesmoke','black'],
	24: ['darkgoldenrod','black'],
	25: ['white','black'],
	26: ['darkgreen','white'],
	27: ['wheat','black'],
	28: ['darkkhaki','black'],
	29: ['violet','black'],
	30: ['darkolivegreen','white'],
	31: ['aquamarine','black'],
	32: ['darkorchid','black'],
	33: ['turquoise','black'],
	34: ['darksalmon','black'],
	35: ['darkseagreen','black'],
	36: ['darkslateblue','black'],
	37: ['darkslategray','white'],
	38: ['darkslategrey','white'],
	39: ['darkturquoise','black'],
	40: ['darkviolet','black'],
	41: ['deeppink','black'],
	42: ['deepskyblue','black'],
	43: ['dimgray','white'],
	44: ['dimgrey','white'],
	45: ['dodgerblue','black'],
	46: ['firebrick','white'],
	47: ['floralwhite','black'],
	48: ['forestgreen','black'],
	49: ['tomato','black'],
	50: ['gainsboro','black'],
	51: ['ghostwhite','black'],
	52: ['gold','black'],
	53: ['goldenrod','black'],
	54: ['azure','white'],
	55: ['grey','white'],
	56: ['blue','white'],
	57: ['greenyellow','black'],
	58: ['honeydew','black'],
	59: ['hotpink','black'],
	60: ['indianred','black'],
	61: ['indigo','white'],
	62: ['ivory','black'],
	63: ['khaki','black'],
	64: ['lavender','black'],
	65: ['lavenderblush','black'],
	66: ['lawngreen','black'],
	67: ['lemonchiffon','black'],
	68: ['lightblue','black'],
	69: ['lightcoral','black'],
	70: ['lightcyan','black'],
	71: ['lightgoldenrodyellow','black'],
	72: ['lightgray','black'],
	73: ['thistle','black'],
	74: ['lightgrey','black'],
	75: ['lightpink','black'],
	76: ['lightsalmon','black'],
	77: ['lightseagreen','black'],
	78: ['lightskyblue','black'],
	79: ['lightslategray','black'],
	80: ['lightslategrey','black'],
	81: ['lightsteelblue','black'],
	82: ['lightyellow','black'],
	83: ['tan','black'],
	84: ['limegreen','black'],
	85: ['linen','black'],
	86: ['magenta','black'],
	87: ['maroon','white'],
	88: ['mediumaquamarine','black'],
	89: ['mediumblue','white'],
	90: ['mediumorchid','black'],
	91: ['mediumpurple','black'],
	92: ['mediumseagreen','black'],
	93: ['mediumslateblue','black'],
	94: ['mediumspringgreen','black'],
	95: ['mediumturquoise','black'],
	96: ['mediumvioletred','black'],
	97: ['midnightblue','white'],
	98: ['mintcream','black'],
	99: ['mistyrose','black'],
	100:['moccasin','black'],
	101:['navajowhite','black'],
	102:['navy','white'],
	103:['oldlace','black'],
	104:['steelblue','black'],
	105:['olivedrab','black'],
	106:['beige','black'],
	107:['orangered','black'],
	108:['orchid','black'],
	109:['palegoldenrod','black'],
	110:['palegreen','black'],
	111:['paleturquoise','black'],
	112:['palevioletred','black'],
	113:['papayawhip','black'],
	114:['peachpuff','black'],
	115:['peru','black'],
	116:['pink','black'],
	117:['plum','black'],
	118:['powderblue','black'],
	119:['bisque','black'],
	120:['green','black'],
	121:['rosybrown','black'],
	122:['royalblue','black'],
	123:['saddlebrown','white'],
	124:['salmon','black'],
	125:['sandybrown','black'],
	126:['seagreen','black'],
	127:['seashell','black'],
	128:['sienna','black'],
	129:['springgreen','black'],
	130:['skyblue','black'],
	131:['slateblue','black'],
	132:['slategray','black'],
	133:['slategrey','black'],
	134:['snow','black'],
	135:['aquamarine','black']
}

color_dict_HiC_node = {
	0:'green',
	1:'red',
	2:'black'
}
color_dict_HiC_edge = {
	1:'gray',
	2:'blue'
}
